window.portfolioData = {
  zh: {
    ui: {
      brandName: "孙千龙",
      navWorks: "作品",
      navExperience: "经历",
      navAbout: "关于",
      navObservation: "观察",
      navDownloads: "下载",
      navContact: "联系",
      heroEyebrow: "Landscape Designer / Melbourne",
      heroTitle: "孙千龙",
      heroSubtitle: "关注城市公共空间、生态系统、场地叙事与可持续城市设计。",
      heroPrimary: "查看经历",
      heroSecondary: "查看作品",
      heroCaption: "旅途风景照片，水岸空间与公共景观氛围",
      worksEyebrow: "Selected Work",
      worksTitle: "作品与项目经历",
      drawingEyebrow: "Drawing & Observation",
      drawingTitle: "手绘、观察与现场表达",
      drawingOne: "皇家植物园观察手绘 01",
      drawingTwo: "皇家植物园观察手绘 02",
      drawingDocEyebrow: "Document",
      drawingDocTitle: "墨尔本大学建筑观察",
      drawingDocText: "作为观察、尺度判断与空间记录能力的补充材料。",
      viewDocument: "查看文件",
      experienceEyebrow: "Experience",
      experienceTitle: "教育、工作经历与专业能力",
      experienceLink: "查看简历文件",
      cvAsideEyebrow: "Profile",
      cvAsideTitle: "景观设计师 / 城市公共空间与植物设计",
      cvSummary:
        "墨尔本大学景观建筑硕士在读，具备观赏园艺专业背景，拥有商业、居住社区、市政基础设施及文化旅游类景观项目经验。擅长空间分析、三维建模与可视化表达，重点关注城市公共空间、植物设计及项目落地。",
      workEyebrow: "Professional Timeline",
      educationEyebrow: "Education",
      educationTitle: "教育背景",
      workTitle: "工作经历",
      skillsTitle: "专业技能",
      courseworkTitle: "代表课程",
      chineseResumeButton: "中文简历",
      aboutEyebrow: "About",
      aboutTitle: "设计关注",
      aboutText:
        "通过场地研究、公共空间策略、生态系统理解与图面表达，将学习阶段的 Studio 项目、手绘观察和作品集资料组织为可持续扩展的个人专业档案。",
      aboutImageCaption: "旅途海岸地貌与边界景观",
      downloadsEyebrow: "Documents",
      downloadsTitle: "简历、作品集与补充资料",
      contactEyebrow: "Contact",
      contactTitle: "开放求职、项目合作与作品交流",
      emailButton: "发送邮件",
      resumeButton: "英文简历",
      footerName: "孙千龙 / Qianlong Sun",
      backTop: "返回顶部",
      openFile: "查看",
      downloadFile: "下载",
      includedDocs: "包含文件",
      roleLabel: "角色",
      typeLabel: "类型",
      gridView: "图像",
      indexView: "索引",
      viewCase: "查看案例",
      closeModal: "关闭",
      projectQuestion: "项目问题",
      projectStrategy: "设计策略",
      projectOutcome: "成果呈现",
      previousSlide: "上一页",
      nextSlide: "下一页",
      openPdf: "打开 PDF"
    },
    filters: [
      { id: "all", label: "全部" },
      { id: "featured", label: "重点" },
      { id: "sustainable", label: "可持续城市主义" },
      { id: "site", label: "场地分析" },
      { id: "public", label: "公共空间" },
      { id: "ecology", label: "生态策略" },
      { id: "drawing", label: "手绘" },
      { id: "archive", label: "归档" }
    ],
    metrics: [
      { value: "5", label: "阶段性 Studio 项目", text: "从设计技法、场地设计到可持续城市主义。" },
      { value: "18+", label: "完整素材文件", text: "PDF、PNG、DOCX 与作品集资料全部纳入网站。" },
      { value: "CN / EN", label: "双语主页", text: "中英文内容结构一致，便于求职与国际交流。" },
      { value: "2024-2026", label: "项目成长路径", text: "按时间组织学习、研究、表达与设计经验。" }
    ],
    experience: {
      education: [
        {
          period: "2024.02 - 至今",
          title: "墨尔本大学 | 景观建筑硕士",
          meta: "澳大利亚墨尔本 / 预计 2026 年 12 月毕业",
          text: "持续推进景观工作室、可持续城市主义、建构生态、景观实践与毕业设计等课程。"
        },
        {
          period: "2018.09 - 2022.06",
          title: "北京林业大学 | 观赏园艺学士",
          meta: "GPA: 85.5/100",
          text: "具备植物、园艺与景观基础背景；获北京林业大学学生社团活动奖学金。"
        }
      ],
      work: [
        {
          period: "2023.05 - 2023.12",
          company: "奥雅设计北京分公司（L&A Design）",
          role: "景观设计助理",
          text: "参与 6 个景观项目，包括 2 个商业街区、2 个居住社区、1 个市政基础设施和 1 个文化旅游项目。",
          tags: ["商业街区", "居住社区", "市政基础设施", "文化旅游"]
        },
        {
          period: "2022.07 - 2023.03",
          company: "无锡协景园艺有限公司",
          role: "景观设计助理",
          text: "完成江苏地区 3 个住宅花园项目的设计并协助施工，参与设计深化与现场实施。",
          tags: ["住宅花园", "设计深化", "现场实施", "植物配置"]
        },
        {
          period: "2021.01 - 2021.02",
          company: "中国城市规划设计研究院（CAUPD）",
          role: "景观设计助理",
          text: "使用 GIS 为海南保亭 4 个村庄制作空间管控图及土地利用规划图，为村庄规划设计提供支持。",
          tags: ["GIS", "村庄规划", "土地利用", "空间管控"]
        }
      ],
      skills: [
        { group: "设计与制图", items: ["AutoCAD", "Rhino", "SketchUp", "3ds Max", "Photoshop"] },
        { group: "可视化表达", items: ["Enscape", "V-Ray"] },
        { group: "空间分析与办公", items: ["ArcGIS", "Microsoft Office"] },
        { group: "新兴工具", items: ["Stable Diffusion", "ComfyUI", "Codex"] }
      ],
      coursework: [
        "GIS in Planning, Design & Development",
        "Plants in the Landscape",
        "Landscape Studio 3: Speculations",
        "Urban and Landscape Heritage",
        "Landscape Detail Design",
        "Landscape Studio 5: Sustainable Urbanism",
        "Landscape Studio 4: Strategies",
        "Constructed Ecologies",
        "Landscape Practice"
      ]
    },
    photos: [
      { src: "assets/photos-web/photo-01.jpg", thumb: "assets/photos-web/photo-01-thumb.jpg", label: "植物温室与林下空间" },
      { src: "assets/photos-web/photo-02.jpg", thumb: "assets/photos-web/photo-02-thumb.jpg", label: "旅途湖面与公共空间氛围" },
      { src: "assets/photos-web/photo-03.jpg", thumb: "assets/photos-web/photo-03-thumb.jpg", label: "植物果实与细部" },
      { src: "assets/photos-web/photo-04.jpg", thumb: "assets/photos-web/photo-04-thumb.jpg", label: "滨水边界" },
      { src: "assets/photos-web/photo-05.jpg", thumb: "assets/photos-web/photo-05-thumb.jpg", label: "旅途海岸风景" },
      { src: "assets/photos-web/photo-06.jpg", thumb: "assets/photos-web/photo-06-thumb.jpg", label: "海岸地貌" },
      { src: "assets/photos-web/photo-07.jpg", thumb: "assets/photos-web/photo-07-thumb.jpg", label: "航拍水岸" },
      { src: "assets/photos-web/photo-08.jpg", thumb: "assets/photos-web/photo-08-thumb.jpg", label: "水面与天空" },
      { src: "assets/photos-web/photo-09.jpg", thumb: "assets/photos-web/photo-09-thumb.jpg", label: "日落水面" },
      { src: "assets/photos-web/photo-10.jpg", thumb: "assets/photos-web/photo-10-thumb.jpg", label: "水杉与湿地边缘" },
      { src: "assets/photos-web/photo-11.jpg", thumb: "assets/photos-web/photo-11-thumb.jpg", label: "夜空与地景" }
    ],
    projects: [
      {
        title: "Landscape Studio 5: Sustainable Urbanism",
        year: "June 2026",
        type: "Featured / Academic Studio",
        role: "Landscape design, urban strategy, visual documentation",
        summary: "以地下水、采石场再生、马术公共活动与城市边缘更新为核心的综合景观城市设计项目。",
        statement: "将受扰动的城市边缘转化为兼具生态修复、公共生活和区域基础设施价值的再生景观。",
        question: "如何让采石场、地下水系统、城市扩张和马术社区从相互冲突的场地条件转化为新的公共景观结构？",
        strategy: "通过物质流、地下水、地形、社区活动和生态缓冲带分析，建立从场地诊断到空间策略的多层系统。",
        outcome: "四组图纸分别呈现基地诊断、系统策略、空间组织和最终表达，可作为首页最重点项目。",
        cover: "assets/thumbs-web/studio5-part1.jpg",
        tags: ["featured", "sustainable", "site", "public", "ecology"],
        keywords: ["Sustainable Urbanism", "Urban Systems", "Public Space"],
        files: [
          { label: "Context / Material Flows", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0001.pdf", thumbnail: "assets/thumbs-web/studio5-part1.jpg" },
          { label: "Systems / Hydrology", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0002.pdf", thumbnail: "assets/thumbs-web/studio5-part2.jpg" },
          { label: "Strategy / Public Realm", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0003.pdf", thumbnail: "assets/thumbs-web/studio5-part3.jpg" },
          { label: "Presentation / Final Boards", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0004.pdf", thumbnail: "assets/thumbs-web/studio5-part4.jpg" }
        ]
      },
      {
        title: "Landscape Studio 4: Strategies",
        year: "Dec 2025",
        type: "Featured / Academic Studio",
        role: "Strategic design, site systems, portfolio presentation",
        summary: "以生态公平和空间优先级判断为线索，展示数据诊断、场地分区和干预策略。",
        statement: "把复杂的社会生态指标转化为空间行动优先级。",
        question: "如何在城市绿地质量、弱势群体需求和生态连通性之间建立更公平的景观干预顺序？",
        strategy: "通过多指标叠加、权重评分和热点识别，定位需要优先改善的区域，并提出对应空间策略。",
        outcome: "形成以生态公平为核心的诊断图谱和场地策略表达。",
        cover: "assets/thumbs-web/studio4-page-1.jpg",
        tags: ["featured", "site", "ecology"],
        keywords: ["Strategy", "Site Systems", "Design Process"],
        files: [
          { label: "第 1 页", path: "Landscape Studio 4 Strategies ( Dec 2025)/2024_JUN.pdf", thumbnail: "assets/thumbs-web/studio4-page-1.jpg" },
          { label: "第 2 页", path: "Landscape Studio 4 Strategies ( Dec 2025)/2024_JUN.pdf", thumbnail: "assets/thumbs-web/studio4-page-2.jpg" }
        ]
      },
      {
        title: "Landscape Studio 3: Speculations",
        year: "June 2025",
        type: "Featured / Academic Studio",
        role: "Speculative design, research framing, visual communication",
        summary: "以 Fitzroy Street Precinct 为对象，探索文化、活动、流线和场地叙事之间的复合关系。",
        statement: "用推演性图像把街区日常活动转译为空间叙事和景观想象。",
        question: "如何把街区中的文化、休闲、涂鸦、运动和儿童艺术等碎片化活动整合为新的公共空间语言？",
        strategy: "通过复合功能、秩序与重叠关系的图面推演，建立面向多元人群的场地叙事框架。",
        outcome: "形成具有实验性和视觉识别度的概念表达，补充作品集中的叙事设计能力。",
        cover: "assets/thumbs-web/studio3-page-01.jpg",
        tags: ["featured", "public", "site"],
        keywords: ["Speculation", "Research", "Landscape Narrative"],
        files: [
          { label: "第 1 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-01.jpg" },
          { label: "第 2 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-02.jpg" },
          { label: "第 3 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-03.jpg" },
          { label: "第 4 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-04.jpg" },
          { label: "第 5 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-05.jpg" },
          { label: "第 6 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-06.jpg" },
          { label: "第 7 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-07.jpg" },
          { label: "第 8 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-08.jpg" },
          { label: "第 9 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-09.jpg" },
          { label: "第 10 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-10.jpg" },
          { label: "第 11 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-11.jpg" },
          { label: "第 12 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-12.jpg" },
          { label: "第 13 页", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-13.jpg" }
        ]
      },
      {
        title: "Landscape Studio 2: Site and Design",
        year: "Dec 2024",
        type: "Academic Studio",
        role: "Site analysis, design development, poster production",
        summary: "聚焦场地阅读与设计转换，展示从基地分析到图纸表达的基础能力。",
        statement: "从场地信息中提炼设计机会，并将其转化为清晰的图面表达。",
        question: "如何通过场地分析识别空间问题，并建立初步设计回应？",
        strategy: "以基地调查、图层分析和设计推导组织项目过程。",
        outcome: "形成完整项目海报，体现早期场地分析和版面表达能力。",
        cover: "assets/thumbs-web/studio2.jpg",
        tags: ["site", "public"],
        keywords: ["Site Analysis", "Design Translation", "Poster"],
        files: [{ label: "Project Poster", path: "Landscape Studio 2： Site and Design (Dec 2024)/QianlongSunPoster00.pdf" }]
      },
      {
        title: "Landscape Studio 1: Design Techniques",
        year: "June 2024",
        type: "Academic Studio",
        role: "Design techniques, representation, foundational workflow",
        summary: "作为景观设计学习路径的起点，展示设计技法、基础图面和表达训练。",
        statement: "建立景观设计的基础工作流：观察、构成、表达和设计技法。",
        question: "如何用基础技法理解景观空间、尺度和表达方式？",
        strategy: "通过设计练习和图面表达训练，建立后续 Studio 项目的基础。",
        outcome: "呈现学习早期的设计方法和视觉表达基础。",
        cover: "assets/thumbs-web/studio1.jpg",
        tags: ["site", "archive"],
        keywords: ["Design Techniques", "Representation", "Foundation"],
        files: [{ label: "Project PDF", path: "Landscape Studio 1 Design Techniques (June 2024)/QianlongSun000.pdf" }]
      },
      {
        title: "Royal Botanic Gardens Observation Drawings",
        year: "2024",
        type: "Drawing / Observation",
        role: "Hand drawing, field observation, spatial recording",
        summary: "通过皇家植物园现场手绘展示观察、构图、尺度判断和景观细部记录能力。",
        statement: "用手绘记录植物、路径、空间层次和现场氛围。",
        question: "如何通过现场观察捕捉景观空间的尺度、植物结构和动线体验？",
        strategy: "以透视、线稿和数字上色结合的方式强化空间表达。",
        outcome: "作为 Studio 项目之外的观察力和表达能力补充。",
        cover: "手绘/皇家植物园1.png",
        tags: ["drawing"],
        keywords: ["Hand Drawing", "Observation", "Field Study"],
        images: ["手绘/皇家植物园1.png", "手绘/皇家植物园2.png"],
        files: []
      },
      {
        title: "University of Melbourne Building Drawing",
        year: "2024",
        type: "Drawing / Observation",
        role: "Architectural observation, drawing documentation",
        summary: "以墨尔本大学建筑观察作为空间记录和手绘表达的补充材料。",
        statement: "以建筑观察训练空间比例、构图和细节表达。",
        question: "如何通过建筑观察增强景观设计中的空间记录能力？",
        strategy: "以手绘和文档整理记录建筑空间的尺度与秩序。",
        outcome: "补充展示跨越建筑与景观的观察表达能力。",
        cover: "assets/thumbs-web/melbourne-building.jpg",
        tags: ["drawing", "archive"],
        keywords: ["Architecture", "Observation", "Drawing"],
        files: [{ label: "Drawing PDF", path: "手绘/墨大建筑.pdf" }]
      },
      {
        title: "Portfolio Archive 2022",
        year: "2022",
        type: "Archive Portfolio",
        role: "Early portfolio, visual archive, design foundation",
        summary: "早期作品集归档，作为个人设计能力发展过程的补充记录。",
        statement: "保留早期作品集，展示设计能力的成长轨迹。",
        question: "如何让历史作品成为个人能力发展路径的一部分，而不是分散文件？",
        strategy: "将早期作品统一归档，作为当前主页的补充材料。",
        outcome: "帮助访客理解从早期表达训练到当前 Studio 项目的连续成长。",
        cover: "assets/thumbs-web/portfolio2022-page-01.jpg",
        tags: ["archive"],
        keywords: ["Archive", "Portfolio", "Early Work"],
        files: [
          { label: "第 1 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-01.jpg" },
          { label: "第 2 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-02.jpg" },
          { label: "第 3 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-03.jpg" },
          { label: "第 4 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-04.jpg" },
          { label: "第 5 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-05.jpg" },
          { label: "第 6 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-06.jpg" },
          { label: "第 7 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-07.jpg" },
          { label: "第 8 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-08.jpg" },
          { label: "第 9 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-09.jpg" },
          { label: "第 10 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-10.jpg" },
          { label: "第 11 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-11.jpg" },
          { label: "第 12 页", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-12.jpg" }
        ]
      }
    ],
    downloads: [
      { title: "Inter / Supporting Material", type: "PDF", path: "CV/Inter.pdf", text: "面试或补充资料文件。" },
      {
        title: "English Resume 2026",
        type: "DOCX",
        path: "CV/Qianlong_Sun_Landscape_Designer_Resume_2026_Refined.docx",
        text: "英文简历 Word 版本。"
      },
      {
        title: "中文简历 2026",
        type: "DOCX",
        path: "CV/孙千龙_景观设计师_中文简历_2026_WPS兼容版.docx",
        text: "中文简历 WPS 兼容版本。"
      },
      { title: "Portfolio 2022", type: "PDF", path: "作品集2022/作品集.pdf", text: "早期作品集归档。" },
      { title: "Studio 1 PDF", type: "PDF", path: "Landscape Studio 1 Design Techniques (June 2024)/QianlongSun000.pdf", text: "Design Techniques 项目文件。" },
      { title: "Studio 2 Poster", type: "PDF", path: "Landscape Studio 2： Site and Design (Dec 2024)/QianlongSunPoster00.pdf", text: "Site and Design 项目海报。" },
      { title: "Studio 3 PDF", type: "PDF", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", text: "Speculations 项目文件。" },
      { title: "Studio 4 PDF", type: "PDF", path: "Landscape Studio 4 Strategies ( Dec 2025)/2024_JUN.pdf", text: "Strategies 项目文件。" },
      { title: "Studio 5 Part 1", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0001.pdf", text: "Sustainable Urbanism 第一组文件。" },
      { title: "Studio 5 Part 2", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0002.pdf", text: "Sustainable Urbanism 第二组文件。" },
      { title: "Studio 5 Part 3", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0003.pdf", text: "Sustainable Urbanism 第三组文件。" },
      { title: "Studio 5 Part 4", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0004.pdf", text: "Sustainable Urbanism 第四组文件。" },
      { title: "Melbourne Building Drawing", type: "PDF", path: "手绘/墨大建筑.pdf", text: "建筑观察手绘文件。" }
    ]
  },
  en: {
    ui: {
      brandName: "Qianlong Sun",
      navWorks: "Works",
      navExperience: "Experience",
      navAbout: "About",
      navObservation: "Observation",
      navDownloads: "Downloads",
      navContact: "Contact",
      heroEyebrow: "Landscape Designer / Melbourne",
      heroTitle: "Qianlong Sun",
      heroSubtitle: "Working across public space, ecological systems, site narratives, and sustainable urbanism.",
      heroPrimary: "View Experience",
      heroSecondary: "View Works",
      heroCaption: "Travel landscape photograph, water edge and public realm atmosphere",
      worksEyebrow: "Selected Work",
      worksTitle: "Works and Project Experience",
      drawingEyebrow: "Drawing & Observation",
      drawingTitle: "Drawing, Observation, and Field Representation",
      drawingOne: "Royal Botanic Gardens Observation Drawing 01",
      drawingTwo: "Royal Botanic Gardens Observation Drawing 02",
      drawingDocEyebrow: "Document",
      drawingDocTitle: "University of Melbourne Building Drawing",
      drawingDocText: "Supplementary material showing observation, scale judgement, and spatial recording.",
      viewDocument: "View Document",
      experienceEyebrow: "Experience",
      experienceTitle: "Education, Professional Experience, and Skills",
      experienceLink: "View Resume Files",
      cvAsideEyebrow: "Profile",
      cvAsideTitle: "Landscape Designer / Urban Public Realm & Planting Design",
      cvSummary:
        "Master of Landscape Architecture candidate at the University of Melbourne with a background in ornamental horticulture and experience across commercial, residential, municipal infrastructure, and cultural tourism landscape projects. Skilled in spatial analysis, 3D modelling, and visualisation, with interests in urban public realm, planting design, and project implementation.",
      workEyebrow: "Professional Timeline",
      educationEyebrow: "Education",
      educationTitle: "Education",
      workTitle: "Professional Experience",
      skillsTitle: "Technical Skills",
      courseworkTitle: "Selected Coursework",
      chineseResumeButton: "Chinese Resume",
      aboutEyebrow: "About",
      aboutTitle: "Design Focus",
      aboutText:
        "This homepage organizes academic studios, hand drawings, portfolio archives, and resume documents into an expandable professional profile built around site research, public-space strategies, ecological thinking, and visual communication.",
      aboutImageCaption: "Travel photograph: coastal landform and edge landscape",
      downloadsEyebrow: "Documents",
      downloadsTitle: "Resume, Portfolio, and Supporting Materials",
      contactEyebrow: "Contact",
      contactTitle: "Open to roles, collaboration, and portfolio conversations",
      emailButton: "Email",
      resumeButton: "English Resume",
      footerName: "Qianlong Sun / 孙千龙",
      backTop: "Back to Top",
      openFile: "Open",
      downloadFile: "Download",
      includedDocs: "Included Files",
      roleLabel: "Role",
      typeLabel: "Type",
      gridView: "Grid",
      indexView: "Index",
      viewCase: "View Case",
      closeModal: "Close",
      projectQuestion: "Project Question",
      projectStrategy: "Design Strategy",
      projectOutcome: "Outcome",
      previousSlide: "Previous",
      nextSlide: "Next",
      openPdf: "Open PDF"
    },
    filters: [
      { id: "all", label: "All" },
      { id: "featured", label: "Featured" },
      { id: "sustainable", label: "Sustainable Urbanism" },
      { id: "site", label: "Site Analysis" },
      { id: "public", label: "Public Space" },
      { id: "ecology", label: "Ecology" },
      { id: "drawing", label: "Drawing" },
      { id: "archive", label: "Archive" }
    ],
    metrics: [
      { value: "5", label: "Academic Studio Projects", text: "From design techniques and site design to sustainable urbanism." },
      { value: "18+", label: "Portfolio Assets", text: "All local PDFs, PNGs, DOCX files, and portfolio documents are included." },
      { value: "CN / EN", label: "Bilingual Homepage", text: "Consistent Chinese and English content for applications and international communication." },
      { value: "2024-2026", label: "Design Development", text: "A chronological path of research, representation, and design growth." }
    ],
    experience: {
      education: [
        {
          period: "Feb 2024 - Present",
          title: "The University of Melbourne | Master of Landscape Architecture",
          meta: "Melbourne, Australia / Expected completion: Dec 2026",
          text: "Current study across landscape studios, sustainable urbanism, constructed ecologies, landscape practice, and thesis preparation."
        },
        {
          period: "Sep 2018 - Jun 2022",
          title: "Beijing Forestry University | Bachelor of Ornamental Horticulture",
          meta: "GPA: 85.5/100",
          text: "Foundation in plants, horticulture, and landscape systems; recipient of the Student Club Activity Scholarship."
        }
      ],
      work: [
        {
          period: "May 2023 - Dec 2023",
          company: "L&A Design Beijing Branch",
          role: "Landscape Design Assistant",
          text: "Contributed to six landscape projects: two commercial precincts, two residential communities, one municipal infrastructure project, and one cultural tourism development.",
          tags: ["Commercial Precincts", "Residential Communities", "Municipal Infrastructure", "Cultural Tourism"]
        },
        {
          period: "Jul 2022 - Mar 2023",
          company: "Wuxi Xiejing Horticulture Co., Ltd.",
          role: "Landscape Design Assistant",
          text: "Designed and supported the construction of three residential garden projects in Jiangsu, contributing from design development through site implementation.",
          tags: ["Residential Gardens", "Design Development", "Site Implementation", "Planting"]
        },
        {
          period: "Jan 2021 - Feb 2021",
          company: "China Academy of Urban Planning and Design",
          role: "Landscape Design Assistant",
          text: "Produced spatial-control and land-use planning maps for four villages in Baoting, Hainan, using GIS to support village planning and design.",
          tags: ["GIS", "Village Planning", "Land Use", "Spatial Control"]
        }
      ],
      skills: [
        { group: "Design & Documentation", items: ["AutoCAD", "Rhino", "SketchUp", "3ds Max", "Photoshop"] },
        { group: "Visualisation", items: ["Enscape", "V-Ray"] },
        { group: "Spatial & Productivity", items: ["ArcGIS", "Microsoft Office"] },
        { group: "Emerging Tools", items: ["Stable Diffusion", "ComfyUI", "Codex"] }
      ],
      coursework: [
        "GIS in Planning, Design & Development",
        "Plants in the Landscape",
        "Landscape Studio 3: Speculations",
        "Urban and Landscape Heritage",
        "Landscape Detail Design",
        "Landscape Studio 5: Sustainable Urbanism",
        "Landscape Studio 4: Strategies",
        "Constructed Ecologies",
        "Landscape Practice"
      ]
    },
    photos: [
      { src: "assets/photos-web/photo-01.jpg", thumb: "assets/photos-web/photo-01-thumb.jpg", label: "Plant house and understory space" },
      { src: "assets/photos-web/photo-02.jpg", thumb: "assets/photos-web/photo-02-thumb.jpg", label: "Travel lake view and public-realm atmosphere" },
      { src: "assets/photos-web/photo-03.jpg", thumb: "assets/photos-web/photo-03-thumb.jpg", label: "Plant fruit and detail" },
      { src: "assets/photos-web/photo-04.jpg", thumb: "assets/photos-web/photo-04-thumb.jpg", label: "Waterfront edge" },
      { src: "assets/photos-web/photo-05.jpg", thumb: "assets/photos-web/photo-05-thumb.jpg", label: "Coastal field observation" },
      { src: "assets/photos-web/photo-06.jpg", thumb: "assets/photos-web/photo-06-thumb.jpg", label: "Coastal landform" },
      { src: "assets/photos-web/photo-07.jpg", thumb: "assets/photos-web/photo-07-thumb.jpg", label: "Aerial shoreline" },
      { src: "assets/photos-web/photo-08.jpg", thumb: "assets/photos-web/photo-08-thumb.jpg", label: "Water and sky" },
      { src: "assets/photos-web/photo-09.jpg", thumb: "assets/photos-web/photo-09-thumb.jpg", label: "Sunset over water" },
      { src: "assets/photos-web/photo-10.jpg", thumb: "assets/photos-web/photo-10-thumb.jpg", label: "Metasequoia and wetland edge" },
      { src: "assets/photos-web/photo-11.jpg", thumb: "assets/photos-web/photo-11-thumb.jpg", label: "Night sky and landscape" }
    ],
    projects: [
      {
        title: "Landscape Studio 5: Sustainable Urbanism",
        year: "June 2026",
        type: "Featured / Academic Studio",
        role: "Landscape design, urban strategy, visual documentation",
        summary: "A comprehensive landscape urbanism project around groundwater, quarry regeneration, equestrian commons, and urban-edge transformation.",
        statement: "Transforming a disturbed urban edge into a regenerative landscape for ecology, public life, and regional infrastructure.",
        question: "How can quarry landscapes, groundwater systems, urban growth, and equestrian communities become a shared public landscape framework?",
        strategy: "The project layers material flows, hydrology, landform, community use, and ecological buffers to move from diagnosis to spatial strategy.",
        outcome: "Four boards document site context, systems thinking, public-realm strategy, and final presentation.",
        cover: "assets/thumbs-web/studio5-part1.jpg",
        tags: ["featured", "sustainable", "site", "public", "ecology"],
        keywords: ["Sustainable Urbanism", "Urban Systems", "Public Space"],
        files: [
          { label: "Context / Material Flows", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0001.pdf", thumbnail: "assets/thumbs-web/studio5-part1.jpg" },
          { label: "Systems / Hydrology", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0002.pdf", thumbnail: "assets/thumbs-web/studio5-part2.jpg" },
          { label: "Strategy / Public Realm", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0003.pdf", thumbnail: "assets/thumbs-web/studio5-part3.jpg" },
          { label: "Presentation / Final Boards", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0004.pdf", thumbnail: "assets/thumbs-web/studio5-part4.jpg" }
        ]
      },
      {
        title: "Landscape Studio 4: Strategies",
        year: "Dec 2025",
        type: "Featured / Academic Studio",
        role: "Strategic design, site systems, portfolio presentation",
        summary: "A strategy-led project using ecological equity, spatial priority, and multi-layer diagnosis to guide intervention.",
        statement: "Turning complex social-ecological indicators into a spatial priority framework.",
        question: "How can green-space quality, vulnerable communities, and ecological connectivity shape a fairer order of landscape intervention?",
        strategy: "The work uses layered indicators, weighted scoring, and hotspot mapping to locate priority areas and propose targeted strategies.",
        outcome: "The project produces a clear diagnostic framework and landscape strategy around ecological equity.",
        cover: "assets/thumbs-web/studio4-page-1.jpg",
        tags: ["featured", "site", "ecology"],
        keywords: ["Strategy", "Site Systems", "Design Process"],
        files: [
          { label: "Page 1", path: "Landscape Studio 4 Strategies ( Dec 2025)/2024_JUN.pdf", thumbnail: "assets/thumbs-web/studio4-page-1.jpg" },
          { label: "Page 2", path: "Landscape Studio 4 Strategies ( Dec 2025)/2024_JUN.pdf", thumbnail: "assets/thumbs-web/studio4-page-2.jpg" }
        ]
      },
      {
        title: "Landscape Studio 3: Speculations",
        year: "June 2025",
        type: "Featured / Academic Studio",
        role: "Speculative design, research framing, visual communication",
        summary: "A speculative project for Fitzroy Street Precinct exploring culture, everyday activity, movement, and site narrative.",
        statement: "Translating everyday urban fragments into an expressive public-space narrative.",
        question: "How can culture, leisure, street art, sport, and children's art be composed into a new landscape language?",
        strategy: "The project works through composite function, disorder, overlap, and speculative mapping to frame a multi-user public realm.",
        outcome: "It adds a vivid narrative and conceptual-design layer to the portfolio.",
        cover: "assets/thumbs-web/studio3-page-01.jpg",
        tags: ["featured", "public", "site"],
        keywords: ["Speculation", "Research", "Landscape Narrative"],
        files: [
          { label: "Page 1", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-01.jpg" },
          { label: "Page 2", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-02.jpg" },
          { label: "Page 3", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-03.jpg" },
          { label: "Page 4", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-04.jpg" },
          { label: "Page 5", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-05.jpg" },
          { label: "Page 6", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-06.jpg" },
          { label: "Page 7", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-07.jpg" },
          { label: "Page 8", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-08.jpg" },
          { label: "Page 9", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-09.jpg" },
          { label: "Page 10", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-10.jpg" },
          { label: "Page 11", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-11.jpg" },
          { label: "Page 12", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-12.jpg" },
          { label: "Page 13", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", thumbnail: "assets/thumbs-web/studio3-page-13.jpg" }
        ]
      },
      {
        title: "Landscape Studio 2: Site and Design",
        year: "Dec 2024",
        type: "Academic Studio",
        role: "Site analysis, design development, poster production",
        summary: "A studio project focused on site reading and design translation from analysis to visual presentation.",
        statement: "Extracting design opportunities from site information and turning them into clear visual communication.",
        question: "How can site analysis reveal spatial issues and support an initial design response?",
        strategy: "The project organizes site investigation, layered analysis, and design translation into a presentation poster.",
        outcome: "A complete poster showing foundational site-analysis and layout skills.",
        cover: "assets/thumbs-web/studio2.jpg",
        tags: ["site", "public"],
        keywords: ["Site Analysis", "Design Translation", "Poster"],
        files: [{ label: "Project Poster", path: "Landscape Studio 2： Site and Design (Dec 2024)/QianlongSunPoster00.pdf" }]
      },
      {
        title: "Landscape Studio 1: Design Techniques",
        year: "June 2024",
        type: "Academic Studio",
        role: "Design techniques, representation, foundational workflow",
        summary: "Foundational design training in techniques, representation, and early landscape design workflows.",
        statement: "Building the foundation of landscape design through observation, composition, representation, and technique.",
        question: "How can foundational techniques support an understanding of landscape space, scale, and visual communication?",
        strategy: "The work uses design exercises and representational studies to establish an early studio workflow.",
        outcome: "A record of early design methods and representational foundations.",
        cover: "assets/thumbs-web/studio1.jpg",
        tags: ["site", "archive"],
        keywords: ["Design Techniques", "Representation", "Foundation"],
        files: [{ label: "Project PDF", path: "Landscape Studio 1 Design Techniques (June 2024)/QianlongSun000.pdf" }]
      },
      {
        title: "Royal Botanic Gardens Observation Drawings",
        year: "2024",
        type: "Drawing / Observation",
        role: "Hand drawing, field observation, spatial recording",
        summary: "Field drawings from the Royal Botanic Gardens showing observation, composition, scale judgement, and landscape detail.",
        statement: "Recording planting, paths, spatial depth, and atmosphere through hand drawing.",
        question: "How can field observation capture landscape scale, vegetation structure, and movement experience?",
        strategy: "Perspective drawing, linework, and digital color are combined to strengthen spatial expression.",
        outcome: "A complementary record of observation and representation beyond academic studio projects.",
        cover: "手绘/皇家植物园1.png",
        tags: ["drawing"],
        keywords: ["Hand Drawing", "Observation", "Field Study"],
        images: ["手绘/皇家植物园1.png", "手绘/皇家植物园2.png"],
        files: []
      },
      {
        title: "University of Melbourne Building Drawing",
        year: "2024",
        type: "Drawing / Observation",
        role: "Architectural observation, drawing documentation",
        summary: "A supplementary observation drawing document focused on architectural space and hand representation.",
        statement: "Using architectural observation to train proportion, composition, and spatial detail.",
        question: "How can architectural observation strengthen spatial recording for landscape design?",
        strategy: "The document records architectural scale and order through drawing and page composition.",
        outcome: "It demonstrates observational skills across architecture and landscape.",
        cover: "assets/thumbs-web/melbourne-building.jpg",
        tags: ["drawing", "archive"],
        keywords: ["Architecture", "Observation", "Drawing"],
        files: [{ label: "Drawing PDF", path: "手绘/墨大建筑.pdf" }]
      },
      {
        title: "Portfolio Archive 2022",
        year: "2022",
        type: "Archive Portfolio",
        role: "Early portfolio, visual archive, design foundation",
        summary: "An early portfolio archive documenting the development of design foundations and visual communication.",
        statement: "Keeping early portfolio work visible as part of a longer design-development path.",
        question: "How can historical work support a coherent professional archive instead of remaining a separate file?",
        strategy: "The archive is integrated as supporting material for understanding earlier design and representation work.",
        outcome: "It helps visitors read the progression from early visual training to current studio work.",
        cover: "assets/thumbs-web/portfolio2022-page-01.jpg",
        tags: ["archive"],
        keywords: ["Archive", "Portfolio", "Early Work"],
        files: [
          { label: "Page 1", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-01.jpg" },
          { label: "Page 2", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-02.jpg" },
          { label: "Page 3", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-03.jpg" },
          { label: "Page 4", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-04.jpg" },
          { label: "Page 5", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-05.jpg" },
          { label: "Page 6", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-06.jpg" },
          { label: "Page 7", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-07.jpg" },
          { label: "Page 8", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-08.jpg" },
          { label: "Page 9", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-09.jpg" },
          { label: "Page 10", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-10.jpg" },
          { label: "Page 11", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-11.jpg" },
          { label: "Page 12", path: "作品集2022/作品集.pdf", thumbnail: "assets/thumbs-web/portfolio2022-page-12.jpg" }
        ]
      }
    ],
    downloads: [
      { title: "Inter / Supporting Material", type: "PDF", path: "CV/Inter.pdf", text: "Interview or supporting material file." },
      {
        title: "English Resume 2026",
        type: "DOCX",
        path: "CV/Qianlong_Sun_Landscape_Designer_Resume_2026_Refined.docx",
        text: "Editable English resume in Word format."
      },
      {
        title: "Chinese Resume 2026",
        type: "DOCX",
        path: "CV/孙千龙_景观设计师_中文简历_2026_WPS兼容版.docx",
        text: "Editable Chinese resume in WPS-compatible Word format."
      },
      { title: "Portfolio 2022", type: "PDF", path: "作品集2022/作品集.pdf", text: "Early portfolio archive." },
      { title: "Studio 1 PDF", type: "PDF", path: "Landscape Studio 1 Design Techniques (June 2024)/QianlongSun000.pdf", text: "Design Techniques project file." },
      { title: "Studio 2 Poster", type: "PDF", path: "Landscape Studio 2： Site and Design (Dec 2024)/QianlongSunPoster00.pdf", text: "Site and Design project poster." },
      { title: "Studio 3 PDF", type: "PDF", path: "Landscape Studio 3： Speculations (June 2025)/QianlongSun.pdf", text: "Speculations project file." },
      { title: "Studio 4 PDF", type: "PDF", path: "Landscape Studio 4 Strategies ( Dec 2025)/2024_JUN.pdf", text: "Strategies project file." },
      { title: "Studio 5 Part 1", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0001.pdf", text: "Sustainable Urbanism file part one." },
      { title: "Studio 5 Part 2", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0002.pdf", text: "Sustainable Urbanism file part two." },
      { title: "Studio 5 Part 3", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0003.pdf", text: "Sustainable Urbanism file part three." },
      { title: "Studio 5 Part 4", type: "PDF", path: "Landscape Studio 5：Sustainable Urbanism (June 2026)/0004.pdf", text: "Sustainable Urbanism file part four." },
      { title: "Melbourne Building Drawing", type: "PDF", path: "手绘/墨大建筑.pdf", text: "Architectural observation drawing document." }
    ]
  }
};
